### PR TITLE
Age dist feature

### PR DESCRIPTION
**Pull request by MableAnnoni**
Edits and additions creating two function; (1) plotting age band distribution for the two periods and (2) table of age band distributions with frequencies for both A and B as well as a sum for both periods.

### CODE REVIEW

**Comment by HorridTom** [comment]
Hi @MableAnnoni ,
Well done this (#2) is great progress! I think you're nearly there with the age distribution feature. Just a few things to sort out first:

1. Could you test the function `plot_age_dist` by running it on the dataframe `clahrcnwlhf::emergency_adms`? What happens if you compare the plot with one that you produce "manually" from the console? When I run the following code, I think I see a discrepancy between the plot generated by `plot_age_dist`, and number shown in the table for e.g. 80-84 period A.
`ea_spells <- clahrcnwlhf::emergency_adms[which(clahrcnwlhf::emergency_adms$new_spell == TRUE),]
table(ea_spells$AgeBand,ea_spells$period.date)`
Have a look and see you agree. If so, can you see what is wrong?
2. Good start on the `plot_dist_table` function - do you have any questions about how to proceed? I can't tell from your pull request (when doing a pull request for review, you could include questions or specific areas where you'd like help).
3. Once we've resolved this, we could consider giving the user more control over the output of `plot_age_dist` - e.g. by allowing them to choose whether to plot across the whole dataset or split by period.

Again well done, have a look tomorrow and if it is helpful for us to Skype I can do so.
Tom.

**Comment by HorridTom** [comment]
As discussed, the line:
```
#dataframe restricted to only rows where 'new.spell' = TRUE
emergency_spells <- clahrcnwlhf::emergency_adms[which(clahrcnwlhf::emergency_adms$new_spell == TRUE),]
```

Should read:

```
#dataframe restricted to only rows where 'new.spell' = TRUE
df <- df[which(df$new_spell == TRUE),]
```


In other words "restrict df to only those rows where new.spell is true, then write this over the top of df".

**Comment by MableAnnoni** [comment]
HI Tom, 
Edits on function 1 done. New function has been committed.

**Comment by HorridTom** [comment]
Great, I checked it and it works for me, well done! We can look at 2 and 3 on Monday/Tuesday next week.

**Comment by MableAnnoni** [comment]
Hi Tom, 
I have added two test functions. They duplicate the original functions and also inlcude the 'IF' 'ELSE' commnads. Also strangly enough, when I plot the graph with the age-band replicemnet command, ageband 100-109 returns a blank graph. 
Kind Regards 
Mable

**Comment by MableAnnoni** [comment]
Hi Tom, 
There was nothing stagged for me to push. So you can commit the changes to the scripit and ill pull them before making any changes 
Kind Reagrads Mable

**Comment by HorridTom** [comment]
Ok Mable thanks, I've done my commit so you can pull now.

**Pull request closed without merging**
